- name: Install Java and Libselinux-python
  include: install_java_and_libselinux.yml
- name: Download and unarchive neo4j file
  unarchive:
    src: http://dist.neo4j.org/neo4j-community-3.0.9-unix.tar.gz
    dest: /usr/local/share/test_neo4j
    remote_src: True
- name: Update Config file
  lineinfile:
    dest: /usr/local/share/neo4j-community-3.0.9/conf/neo4j.conf
    regexp: '^#org\.neo4j\.server\.webserver\.address=0\.0\.0\.0'
    line: 'org.neo4j.server.webserver.address=0.0.0.0'
- name: Turn off login security on neo4j browser
  lineinfile:
    dest: /usr/local/share/neo4j-community-3.0.9/conf/neo4j.conf
    regexp: '^#dbms.security.auth_enabled=false'
    line: 'dbms.security.auth_enabled=false'
- name: Update https.enabled to false
  lineinfile:
    dest: /usr/local/share/neo4j-community-3.0.9/conf/neo4j.conf
    regexp: '^dbms.connector.https.enabled=true'
    line: 'dbms.connector.https.enabled=false'
- name: Uncomment http.address and set to open 0.0.0.0
  lineinfile:
    dest: /usr/local/share/neo4j-community-3.0.9/conf/neo4j.conf
    regexp: '^#dbms\.connector\.http\.address=0\.0\.0\.0:7474'
    line: 'dbms.connector.http.address=0.0.0.0:7474'
# TODO- name: Add 'neos' and 'neop' aliases

wget dist.neo4j.org/neo4j-community-3.0.9-unix.tar.gz
echo unzipping
tar -xzf neo4j-community-3.0.9-unix.tar.gz
# echo renaming to 'neo4j/'
# mv neo4j-community-2.3.9 neo4j
echo updating config file
sed -i.bak s/#org.neo4j.server.webserver.address=0.0.0.0/org.neo4j.server.webserver.address=0.0.0.0/g neo4j-community-3.0.9/conf/neo4j.conf
sed -i.bak s/#dbms.security.auth_enabled=false/dbms.security.auth_enabled=false/g neo4j-community-3.0.9/conf/neo4j.conf
sed -i.bak s/dbms.connector.https.enabled=true/dbms.connector.https.enabled=false/g neo4j-community-3.0.9/conf/neo4j.conf
sed -i.bak s/#dbms.connector.http.address=0.0.0.0:7474/dbms.connector.http.address=0.0.0.0:7475/g neo4j-community-3.0.9/conf/neo4j.conf
# echo moving neo4j files into test location
# sudo mv /test_neo4j/neo4j /test_neo4j/neo4j_test_200_backup
# sudo mv neo4j /test_neo4j/.
# echo changing permissions
# sudo chown root:root /test_neo4j/neo4j
