- name: Install Git
  become: true
  yum:
    name: git
    state: latest

# Install needed packages involving database connections
# - name: Install Oracle Instant Client for ruby oci8 gem for Banner
#   become: true
#   include: oracle_instant_client.yml
# - name: install free-tds requirement
#   become: true
#   yum:
#     name: freetds
#     state: latest
#   yum:
#     name: freetds-devel
#     state: latest

# Configure Git
- name: add color to git output
  command: git config --global color.ui true
- name: add github username
  command: git config --global user.name {{git_user_name}}
- name: add github email
  command: git config --global user.email {{git_email}}

# install extra global gems
- name: install extra global gems
  command: rvm @global do gem install {{item}}
  with_items:
    - bundler
    - rubocop
    - brakeman
    - haml_lint
    - flog

# install npm
- name: install npm
  become: true
  yum:
    name: npm
    state: latest

# Create housing directory and clone Application
# - name: create directory to house application
#   file:
#     path: /vagrant/YOUR_APPLICATION_NAME
#     state: directory
# - name: Ensure repo exists on box
#   git:
#     repo: git@bitbucket.org:notredameregistrar/eforms.git
#     dest: /vagrant/YOUR_APPLICATION_NAME
#     accept_hostkey: true
#     update: no
