---
- hosts: all
  sudo: true
  tasks:
    - name: install development tools
      include: yum_development_tools.yml
- hosts: all
  vars:
    ruby_version: 2.3.4
  roles:
    - role: rvm_io.ruby
      rvm1_rubies:
        - ruby-{{ruby_version}}
      rvm1_user: 'vagrant'
      tags: ruby
  tasks:
  - name: install git and checkout application repo
    include: checkout_application.yml
